trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - segunss-patch-1

jobs:
- template: image-generation.yml
  parameters:
    image_type: windows2022
    image_readme_name: Windows2022-Readme.md